### ISSUE TITLE
illegalKeySizeException with Device.sendSMS()

### ISSUE THREAD

**Issue by ghost** [Sheigutn/pushbullet-java-8#1]
Hey,

Great API.
I keep hitting one issue though. When I try to use Device.sendSMS() it returns "InvalidKeyException: Illegal key size"
The code that leads up to the sendSMS line is below:

```
String message="#########";
String number="+447#########";
String token="###########";
String passwd="########";


Pushbullet pushB=new Pushbullet(token,passwd);
Device phone=pushB.getDevice(config.getProperty("PhoneID"));
phone.sendSMS(number, message);
```

Also phone.isActive() returns true
and phone.pushNote() works perfectly.

The error is then thrown on the sendSMS() line. Full Stack trace below...

`java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    at javax.crypto.Cipher.implInit(Cipher.java:805)
    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    at javax.crypto.Cipher.init(Cipher.java:1396)
    at javax.crypto.Cipher.init(Cipher.java:1327)
    at com.github.sheigutn.pushbullet.cryptography.Encryption.encrypt(Encryption.java:102)
    at com.github.sheigutn.pushbullet.cryptography.EphemeralEncryptionHandler$EncryptionEphemeralTypeAdapter.write(EphemeralEncryptionHandler.java:42)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:112)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:239)
    at com.google.gson.Gson.toJson(Gson.java:661)
    at com.google.gson.Gson.toJson(Gson.java:640)
    at com.google.gson.Gson.toJson(Gson.java:595)
    at com.google.gson.Gson.toJson(Gson.java:575)
    at com.github.sheigutn.pushbullet.http.defaults.post.SendEphemeralRequest.applyBody(SendEphemeralRequest.java:39)
    at com.github.sheigutn.pushbullet.http.defaults.post.SendEphemeralRequest.applyBody(SendEphemeralRequest.java:14)
    at com.github.sheigutn.pushbullet.Pushbullet.executeRequest(Pushbullet.java:791)
    at com.github.sheigutn.pushbullet.Pushbullet.pushEphemeral(Pushbullet.java:716)
    at com.github.sheigutn.pushbullet.Pushbullet.pushEphemeral(Pushbullet.java:707)
    at com.github.sheigutn.pushbullet.items.device.Device.sendSMS(Device.java:148)
    at pushBullet.PushBulletBot.sendPM(PushBulletBot.java:82)`

**Comment by Sheigutn** [comment]
Oh, seems like I missed that in the readme. To be able to use e2e-encryption you have to install the Unlimited Strength Jurisdiction Policy Files that you can find here: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by ghost** [comment]
Thanks so much. Works perfectly now :)
